# Generated by Django 4.2.7 on 2024-01-31 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_quantity', models.IntegerField(default=10)),
                ('pass_length', models.IntegerField(default=12)),
                ('include_digits', models.BooleanField(default=True)),
                ('include_lowercase', models.BooleanField(default=True)),
                ('include_uppercase', models.BooleanField(default=True)),
                ('include_symbols', models.BooleanField(default=True)),
                ('custom_symbols', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
