# Generated by Django 4.2.7 on 2024-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_keeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
